/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    // background colors

    //Tailwind purges these classes by default, so we need to add them to the safelist to prevent them from being removed.
    "bg-theme-1",
    "bg-theme-1/30",
    "bg-theme-2",
    "bg-theme-2/30",
    "bg-theme-3",
    "bg-theme-3/30",
    "bg-theme-4",
    "bg-theme-4/30",
    "bg-theme-5",
    "bg-theme-5/30",
    "bg-theme-6",
    "bg-theme-6/30",
    "bg-theme-7",
    "bg-theme-7/30",
    "bg-theme-1/20",
    "bg-theme-2/20",
    "bg-theme_3/20",
    "bg-theme-4/20",
    "bg-theme-5/20",
    "bg-theme-6/20",
    "bg-theme-7/20",
    "bg-theme-1/50",
    "bg-theme-2/50",
    "bg-theme-3/50",
    "bg-theme-4/50",
    "bg-theme-5/50",
    "bg-theme-6/50",
    "bg-theme-7/50",

    // text colors
    "text-theme-1",
    "text-theme-2",
    "text-theme-3",
    "text-theme-4",
    "text-theme-5",
    "text-theme-6",
    "text-theme-7",

    // border/hover/other variants
    "border-theme-1",
    "border-theme-2",
    "border-theme-3",
    "border-theme-4",
    "border-theme-5",
    "border-theme-6",
    "border-theme-7",
    "hover:border-theme-1",
    "hover:border-theme-2",
    "hover:border-theme-3",
    "hover:border-theme-4",
    "hover:border-theme-5",
    "hover:border-theme-6",
    "hover:border-theme-7",
    "hover:border-theme-1/70",
    "hover:border-theme-2/70",
    "hover:border-theme-3/70",
    "hover:border-theme-4/70",
    "hover:border-theme-5/70",
    "hover:border-theme-6/70",
    "hover:border-theme-7/70",
    "focus:border-theme-1",
    "focus:border-theme-2",
    "focus:border-theme-3",
    "focus:border-theme-4",
    "focus:border-theme-5",
    "focus:border-theme-6",
    "focus:border-theme-7",
    "focus:!ring-theme-1",
    "focus:!ring-theme-2",
    "focus:!ring-theme-3",
    "focus:!ring-theme-4",
    "focus:!ring-theme-5",
    "focus:!ring-theme-6",
    "focus:!ring-theme-7",
    "focus-visible:!border-theme-1",
    "focus-visible:!border-theme-2",
    "focus-visible:!border-theme-3",
    "focus-visible:!border-theme-4",
    "focus-visible:!border-theme-5",
    "focus-visible:!border-theme-6",
    "focus-visible:!border-theme-7",
    "peer-checked:bg-theme-1/30",
    "peer-checked:bg-theme-2/30",
    "peer-checked:bg-theme-3/30",
    "peer-checked:bg-theme-4/30",
    "peer-checked:bg-theme-5/30",
    "peer-checked:bg-theme-6/30",
    "peer-checked:bg-theme-7/30",
    "peer-checked:text-theme-1",
    "peer-checked:text-theme-2",
    "peer-checked:text-theme-3",
    "peer-checked:text-theme-4",
    "peer-checked:text-theme-5",
    "peer-checked:text-theme-6",
    "peer-checked:text-theme-7",
    "peer-checked:border-theme-1",
    "peer-checked:border-theme-2",
    "peer-checked:border-theme-3",
    "peer-checked:border-theme-4",
    "peer-checked:border-theme-5",
    "peer-checked:border-theme-6",
    "peer-checked:border-theme-7",
    "disabled:hover:bg-transparent",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
